services:
  optimizer:
    image: kernelmachine/optimizer:latest
    ports:
      - "8000:8000"
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    env_file:
      - ./default.env